/* Current tests */
#include "tests/TestClearColor.h"
#include "tests/TestTriangle.h"
#include "tests/TestSquare.h"
#include "tests/Test3DBasics.h"
#include "tests/TestLighting.h"
#include "tests/TestMaterials.h"
#include "tests/TestLightingMaps.h"
#include "tests/TestShaders.h"
#include "tests/TestLightCaster.h"
